---
title: "Fichas metodologicas para indicadores fiscales"

author: "Alex Bajaña"
date: "2022-10-22"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

***
### Datos del Indicador


#### Nombre del Indicador:  

Tratamiento continuo de uso de paraísos fiscales (nivel 2014)

***
#### Definición

Dado el porcentaje de participación efectiva con residencia en paraisos fiscales que declaran las sociedades se toma el valor correspondiente al año 2014.

***
#### Fórmula del cálculo


$$PF14_{i} = \sum_i^n{p_{it=2014}}$$

Donde:

p_{it}: participación efectiva en paraísos fiscales de la empresa i en el año t = 2014

i: beneficiarios finales en paraísos fiscales

PF14_{i}: participación de los beneficiarios finales con residencia en paraísos de las empresas durante el año 2014 


***


***
#### Definición de las variables involucradas

Para el cálculo del tratamiento a nivel 2014 de uso de paraísos fiscales, se tomará en cuenta:

•	Anexo APS:

–	Porcentaje efectivo de participacion: es el porcentaje de propiedad en la emmpresa informante que tiene cada beneficiario final declarado o informado en el Anexo APS

–	Identificador del informante Identificador anónimo de la empresa informante

–	Año fiscal: año fiscal declarado en el Anexo APS


***
#### Metodología de cálculo

1.	Se determinan las sociedades que hayan declarado impuesto a la renta en los años del periodo

2.	Se excluyen aquellas empresas que presentan inconsistencias en la declaración.

3.	Se filtran los datos para el año 2014




#### Limitaciones técnicas

*	Se considera a todos los informantes del Anexo APS que hayan declarado formulario al impuesto a la renta.

*	Para el análisis no se consideran las correcciones en la presentación de años pasados.

*	La tasa de omisión del anexo APS información se presenta a continuación:


*** 

#### Unidad de medida del indicador

Porcentaje de participaciòn

***

####  Interpretación del indicador

Participación efectiva en paraisos fiscales en el año 2014

***

### Metadatos

#### Fuente de información

Anexo APS

#### Periodicidad del indicador y de las variables

Anual

#### Disponibilidad de los datos

Desde el 2012 al 2020


#### Relación con instrumentos de planificación nacional o acuerdos, iniciativas internacionales

*	Ley Orgánica de Régimen Tributario Interno (LORTI)

*	Reglamento para la aplicación de la Ley Orgánica de Régimen Tributario Interno (RALORTI)

#### Periodo de elaboración

Octubre, 2022

*** 




