---
title: "1.Indicadorconcentración de paraísos fiscales"

author: "Alex Bajaña"
date: "2022-10-22"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

***
## FICHA METODOLÓGICA
***

#### Nombre del Indicador:  
Tratamiento continuo de uso de paraísos fiscales"

***
#### Definición
El promedio de la participación directa en paraisos fiscales del período 2012-2014.

***
## Fórmula del cálculo
***

$$P = \sum_i^n{p_{i}/n}$$

Donde:

P : participación efectiva en paraísos fiscales

i : beneficiarios finales en paraísos fiscales

$\sum_i^n{p_{i}/n}$ : promedio de la participación de los beneficiarios finales en los paraisos fiscales dentro de las empresas por el periodo 

***


***
## DEFINICIÓN DE LAS VARIABLES RELACIONADAS
***

Para el cálculo del tratamiento continuo de uso de paraísos fiscales, se tomará en cuenta:

* **Porcentaje efectivo de participacion**: es el porcentaje de propiedad en la emmpresa informante que tiene cada individuo declarado o informado en el Anexo APS

* **Identificador del informante** es la empresa informante

* **Año fiscal**: año fiscal declarado

***
## METODOLOGÍA DE CÁLCULO
***

Es el promedio de la participacion efectiva declarada por el informante

$$P = \sum_i^n{p_{i}/n}$$


#### LIMITACIONES TÉCNICAS

Se considera a todos los informantes del Anexo APS que hayan declarado formulario al impuesto a la renta.

#### UNIDAD DE MEDIDA DEL INDICADOR

porcentaje promedio

#### INTERPRETACIÓN DEL INDICADOR

Participación promedio que tienen las empresas en paraísos fiscales durante el periodo 2012-2014

#### FUENTE DE DATOS

Anexo APS

#### PERIODICIDAD DEL INDICADOR Y LAS VARIABLES

Anual

#### DISPONIBILIDAD DE LOS DATOS

Desde el 2012 al 2020


#### RELACIÓN CON INSTRUMENTOS DE PLANIFICACIÓN NACIONAL O ACUERDOS, INICIATIVAS INTERNACIONALES

Normas que rigen la presentación del Anexo APS y Ley Orgánica de Régimen Tributario Interno (LORTI)

#### FECHA DE ELABORACIÓN DE LA FICHA METODOLÓGICA

09/10/2022




***
## TABLA QUE CONTIENE INFORMACIÓN ESTADISTICA DESCRIPTIVA
***

